### ISSUE TITLE
clipton freezes every few weeks

### ISSUE THREAD

**Issue by vaygr** [madprops/clipton#1] opened 2023-04-28 18:17 UTC
Not sure if you noticed this, but clipton is freezing every couple of weeks on my system.

I thought that was due to URL fetching, but no, the issue persisted after I disabled it.

At the time I also noticed `copyevent` wasn't running.

**Comment by madprops** [comment] 2023-04-29 03:07
I have not noticed this. Working fine here on x11.

I have these defaults:

```
# How many items to store in the file
max_items = 2000

# Don't save to file if char length exceeds this
heavy_paste = 5000
```

Wonder if restarting the service fixes it.

I usually don't go more than 2 weeks of usage though since I upgrade the system every couple of weeks or so.

When that happens, running it from the terminal might yield some output.

`/usr/bin/clipton` or `python /path/clipton.py`

I'm planning on removing copyevent for clipnotify as soon as clipnotify gets updated on arch.

**Comment by vaygr** [comment] 2023-04-29 03:43
Thanks! Yeah, I'm planning to run it in foreground and see what I can find.

**Comment by madprops** [comment] 2023-04-30 20:17
Btw when you say it freezes, do you mean the watcher process, or the client process when you try to see open the manager? Does your cpu spike to high levels?

**Comment by vaygr** [comment] 2023-04-30 20:54
The watcher. When I copy stuff, and then open the client process it shows history from the last time it was working.

**Comment by madprops** [comment] 2023-04-30 21:14
Did you check with `ps aux | grep clipton` to see if the watcher was still running?
Sometimes it happens to me that the watcher process dies or hasn't been started.
I'll check if adding try/catch blocks on the loop is a good idea. 
But I want to avoid accidental infinite loops if copyevent fails to block the loop.

**Comment by madprops** [comment] 2023-04-30 21:21
I added a try/except block which might block some exceptions that happen for an unknown reason:

```python
    try:
      clip = os.popen("xclip -o -sel clip").read()
      print(f"clip: {clip}")
      get_items()
      add_item(clip)
    except Exception as err:
      print(err)
```

copyevent is left as is to avoid infinite loops, so if that throws an exception it also brings down the watcher. 
But not sure why that would happen.

**Comment by madprops** [comment] 2023-05-31 02:41
Crashed here. Not sure what happened. I'll add saving to text log files on exceptions.

**Comment by madprops** [comment] 2023-05-31 03:34
https://github.com/madprops/clipton/blob/main/clipton.py#L265

Changed the way the commands in the watcher get executed.
And added systemd logs which can be viewed with:

```
journalctl --user -b -u clipton.service | tail
```

**Comment by madprops** [comment] 2023-06-15 04:12
I think the problem is xclip. I think it's buggy and it just hangs sometimes. Because right now it just crashed and when I checked copyevent was not running , but xclip was. What I did was give xclip a 3 second timeout, so if it fails it just dies after 3 seconds and the next iteration kicks in.
![xclip](https://github.com/madprops/clipton/assets/206498/f5c62c69-849a-44c6-a2c5-a2e2404f302d)

**Comment by vaygr** [comment] 2023-06-15 04:16
That's exactly what I was seeing. xclip was on.

**Comment by madprops** [comment] 2023-07-21 03:53
I haven't had a crash in a while, I think it's fixed. Make sure to update/install the aur package just in case. Thanks, I'm closing this.

**Closed as completed by madprops** 2023-07-21 03:53 UTC

**Comment by vaygr** [comment] 2023-07-21 05:11
Same here, thanks again!

**Comment by vaygr** [comment] 2024-04-05 17:51
Started seeing this issue again (but maybe it required more time). clipton watcher froze at `read()` 3 days ago. No xclip processes this time.

**Comment by madprops** [comment] 2024-04-05 20:16
I'm gonna try by adding this:

`socket.setdefaulttimeout(CMD_TIMEOUT)`

That's supposed to give a timeout to `urlopen` assuming that was the read that froze.

Lets see if it works.

**Comment by vaygr** [comment] 2024-04-05 20:26
Oh, okay. So my version was from db95e7b. Can you release a new tarball so I can distro-package it?

**Comment by madprops** [comment] 2024-04-05 20:28
Released v45 just now.

**Comment by vaygr** [comment] 2024-06-21 17:45
Hmm, not sure what happened. Maybe I never looked at the logs recently, but when I did I saw this every second:

```
Jun 21 10:36:11 clipton[585757]: Error: target STRING not available
Jun 21 10:36:19 clipton[586383]: Error: target STRING not available
Jun 21 10:36:20 clipton[586497]: Error: target STRING not available
Jun 21 10:36:21 clipton[586520]: Error: target STRING not available
Jun 21 10:36:21 clipton[586542]: Error: target STRING not available
Jun 21 10:36:22 clipton[586625]: Error: target STRING not available
Jun 21 10:36:23 clipton[586670]: Error: target STRING not available
Jun 21 10:36:23 clipton[586700]: Error: target STRING not available
Jun 21 10:36:24 clipton[586787]: Error: target STRING not available
```

Thought existing items/settings was a problem, but no. Maybe it popped up when I upgraded to Python 3.12..

**Comment by madprops** [comment] 2024-06-21 22:41
I think that's just an xclip error that happens when you copy a binary file, afaik there's no way to catch it / silence it

**Comment by vaygr** [comment] 2024-06-21 22:45
Understood, thanks.
